### ISSUE TITLE
Change a slider visibility

### ISSUE THREAD

**Issue by BrianLima** [zubetto/ColorControl#2]
Would it be possible to have a property where I could set the "AlphaSlider" visibility to hiden?

**Comment by zubetto** [comment]
Sorry for the delay!
In the _ColorControlPanel.xaml_ you can set Visibility property of the **dockAlpha** _DockPanel_ to the _Hidden_
OR
Try to use files in the attachment in which I added new dependency property _DockAlphaVisibility_ (but I not tested it yet)
[ColorTools.zip](https://github.com/zubetto/ColorControl/files/1256961/ColorTools.zip)

**Comment by BrianLima** [comment]
Seems to work okay, can you push this into release?

**Comment by zubetto** [comment]
I think yes, but there is small issue. In spite of the fact that the alpha slider can be hidden, users will still be able to change alpha by the color code. Is it essential?

**Comment by BrianLima** [comment]
Not essential, in my use case only the R, G and B channels are usefull. Hidindg the A slider does the job for me.
